---
- name: Join all VPS to Tailscale
  hosts: all
  become: true

  vars_prompt:
    - name: tailscale_auth_key
      prompt: "Enter Tailscale Auth Key"
      private: true

  tasks:
    - name: Join Tailscale network
      command: tailscale up --authkey={{ tailscale_auth_key }}
      register: tailscale_up

    - name: Show result
      debug:
        var: tailscale_up.stdout