# tinyproxy-config.yml
---
- name: Configure TinyProxy
  hosts: bwh-minichicken-05-22
  become: true

  vars:
    tinyproxy_port: 3128
    tinyproxy_user: osu
    tinyproxy_password: osuinstack

  tasks:
    - name: Set TinyProxy port
      ansible.builtin.lineinfile:
        path: /etc/tinyproxy/tinyproxy.conf
        regexp: '^Port '
        line: "Port {{ tinyproxy_port }}"
      notify: Restart TinyProxy

    - name: Bind TinyProxy to Tailscale IP
      ansible.builtin.lineinfile:
        path: /etc/tinyproxy/tinyproxy.conf
        regexp: '^#?Listen '
        line: "Listen {{ tailscale_ip }}"
      notify: Restart TinyProxy

    - name: Allow Tailscale network
      ansible.builtin.lineinfile:
        path: /etc/tinyproxy/tinyproxy.conf
        line: "Allow 100.64.0.0/10"
        insertafter: '^Allow 127\.0\.0\.1'
        state: present
      notify: Restart TinyProxy

    - name: Set BasicAuth
      ansible.builtin.lineinfile:
        path: /etc/tinyproxy/tinyproxy.conf
        regexp: '^#?BasicAuth '
        line: "BasicAuth {{ tinyproxy_user }} {{ tinyproxy_password }}"
      notify: Restart TinyProxy

  handlers:
    - name: Restart TinyProxy
      ansible.builtin.systemd:
        name: tinyproxy
        state: restarted